package mazesolver;

/**
 * Contains static variables which are used for configuration purposes.
 */
public class Settings {
    
    /**
     * Contains all settings for the Main and Director class.
     */
    public static class Main {
        
        // Use multiThreading in solving the Route and SubRoute classes
        public static boolean multiThreading = false;
        
        // Maximum number of total iterations
        public static int maxIterations = 50;
        
        // Live status updates generated by the application
        public static boolean showLog = true;
        public static boolean showDebug = false;
        
        // Location of the maze files
        public static String mazeFile = "example_maze.txt";
        public static String coordinatesFile = "example_coords.txt";
        public static String venuesFile = "example_venues.txt";
        public static String visitsFile = null;
    }

    /**
     * Contains all settings for the Graphics class.
     */
    public static class Graphics {
        
        // Window title
        public static String title = "Maze Solver | Pathfinding and the TSP";
        
        // Window dimensions
        public static int width = 800;
        public static int height = 600;
        
        // Time between draws and window update rate
        public static int drawWaitTime = 1000;
        
        // Drawing settings
        public static int lineWidth = 3;
        public static float[] lineColor = {1, 0, 0};
    }
    
    /**
     * Contains all settings for the Route class.
     */
    public static class Route {
        
        // Genetic algorithm settings
        public static int populationSize = 500;
        public static int generationsPerRun = 500;
        
        // Probability values for crossover and mutation
        public static float crossoverOdds = 0.7f;
        public static float invertOdds = 0.1f;
        public static float shuffleOdds = 0.01f;
        public static float swapOdds = 0.01f;
        
    }
    
    /**
     * Contains all settings for the SubRoute class.
     */
    public static class SubRoute {
        // Size of the ant flock released every iteration
        public static int flockSize = 10;
    }
    
    /**
     * Contains all settings for the Ant class.
     */
    public static class Ant {
        // Factor of interest for specific node types
        public static int factorWall = 0;
        public static int factorReverse = 2;
        public static int factorOld = 1000;
        public static int factorNew = 100000;
        
        // Maximum number of steps per ant
        public static int maxSteps = 40000;        
    }
    
}
