
package Factorzations;

import BigIntegers.AprtCleInteger;
import BigIntegers.LargeInteger;
import static BigIntegers.LargeInteger.isPrime;
import Factorzations.ecm.ECM;
import Factorzations.siqs.Siqs;
import static Factorzations.siqs.StaticFunctions.isProbablePrime;
import calculator.Deque;
import calculator.EmptyDequeException;
import calculator.EncodedOperation;

import calculator.largemodel.Add;
import calculator.largemodel.Divide;
import calculator.largemodel.Multiply;
import calculator.largemodel.Power;
import calculator.largemodel.Remainder;
import calculator.largemodel.Subtract;

import static BigIntegers.FactorInteger.TYP_AURIF;
import static BigIntegers.FactorInteger.TYP_EC;
import static BigIntegers.FactorInteger.TYP_LEHMAN;
import static BigIntegers.FactorInteger.TYP_SIQS;

import ecm.Checks.FibonacciCheck;
import ecm.Checks.LucasCheck;
import ecm.Checks.PowerCheck;
import ecm.Checks.PowerPM1Check;
import ecm.PrimeTest.AprtCle;

import java.math.BigInteger;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author spy
 */
public class GUI extends javax.swing.JFrame {
    private Deque theStack = new Deque();
    private EncodedOperation op = null;
    private AprtCleInteger N;
    
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bigNumber = new javax.swing.JTextField();
        Factor = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Power = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Up = new javax.swing.JButton();
        Down = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        Rem = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        Divide = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Sign = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Multiply = new javax.swing.JButton();
        Sub = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Enter = new javax.swing.JButton();
        Mobius = new javax.swing.JButton();
        Totient = new javax.swing.JButton();
        Sum = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bigNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bigNumberActionPerformed(evt);
            }
        });

        Factor.setText("Factor");
        Factor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FactorActionPerformed(evt);
            }
        });

        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        Power.setText("x^y");
        Power.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowerActionPerformed(evt);
            }
        });

        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Up.setText("Up");
        Up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpActionPerformed(evt);
            }
        });

        Down.setText("Down");
        Down.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownActionPerformed(evt);
            }
        });

        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });

        Rem.setText("Rem");
        Rem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemActionPerformed(evt);
            }
        });

        jButton10.setText("2^x");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("10^x");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        Divide.setText("/");
        Divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivideActionPerformed(evt);
            }
        });

        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Sign.setText("+/-");
        Sign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignActionPerformed(evt);
            }
        });

        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Multiply.setText("*");
        Multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplyActionPerformed(evt);
            }
        });

        Sub.setText("-");
        Sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubActionPerformed(evt);
            }
        });

        Add.setText("+");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Enter.setText("=");
        Enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterActionPerformed(evt);
            }
        });

        Mobius.setText("Mobius");
        Mobius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MobiusActionPerformed(evt);
            }
        });

        Totient.setText("Totient");
        Totient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotientActionPerformed(evt);
            }
        });

        Sum.setText("Sum");
        Sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bigNumber)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Clear, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Up, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Down, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Delete, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Sum, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Factor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Power, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton10, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton11, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Rem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Mobius, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Totient, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Sign)
                                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton8)
                                    .addComponent(jButton5)
                                    .addComponent(jButton2)
                                    .addComponent(jButton0))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton9)
                                    .addComponent(jButton6)
                                    .addComponent(jButton3)
                                    .addComponent(Enter))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Add)
                                    .addComponent(Sub)
                                    .addComponent(Multiply)
                                    .addComponent(Divide))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bigNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Clear)
                    .addComponent(Up)
                    .addComponent(Down)
                    .addComponent(Delete)
                    .addComponent(Sum)
                    .addComponent(Factor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Power)
                    .addComponent(jButton10)
                    .addComponent(jButton11)
                    .addComponent(Rem)
                    .addComponent(Mobius)
                    .addComponent(Totient))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(Divide))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(Multiply))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(Sub))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sign)
                    .addComponent(jButton0)
                    .addComponent(Enter)
                    .addComponent(Add))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bigNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bigNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bigNumberActionPerformed

    private void FactorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FactorActionPerformed
        //Classical classical = new Classical(new BigInteger(bigNumber.getText()));
        N = new AprtCleInteger(bigNumber.getText());
        if(N.compareTo(BigInteger.TWO) < 0) return;
        if (N.GetSmallFactors(0) != 1){
            N.addSelf2PD();
            LucasCheck lucas = new LucasCheck(N);
            FibonacciCheck fibo = new FibonacciCheck(N);
            PowerPM1Check power = new PowerPM1Check(N);
            int index = lucas.Check();
            if(index > 0) lucas.Factor(index, N.getPD(N.NbrFactors - 1));
            index = fibo.Check();
            if(index > 0) fibo.Factor(index, N.getPD(N.NbrFactors - 1));
            if(power.Check()){
                if(N.Base == 2 && N.exp < 0 && isProbablePrime(Math.abs(N.exp))){
                    System.out.println(N.Base + "," + N.exp);
                    N.isPrime = isPrime(Math.abs(N.exp));
                    System.out.println(N.isPrime);
                    if(N.isPrime) return;
                }
            }
            for(int i = 0; i < N.NbrFactors; i++){
                Checks(N, i);
                int EC = N.getType(i);
                if (EC > 0 && EC < TYP_EC && EC != TYP_AURIF && EC != TYP_SIQS && EC != TYP_LEHMAN){ /* Composite */
                    AprtCleInteger n = new AprtCleInteger(N.getPD(i).toString());
                    ECM ecm = new ECM(n);
                    BigInteger NN = ecm.factor();
                    if(NN == BigInteger.ONE){
                        Siqs siqs = new Siqs(n);
                        NN = siqs.factor();
                        N.InsertNewFactor(NN, EC);
                    } else {
                        N.InsertNewFactor(NN, EC);
                    }
                    i--;
                }
            }
        }
        for(int i = 0; i < N.NbrFactors - 1; i++)
            System.out.print(N.getPD(i) + "x");
        System.out.println(N.getPD(N.NbrFactors - 1));
        if(N.ComputeFourSquares()){
            BigInteger sum = BigInteger.ZERO;
            for (BigInteger Quad : N.Quad) {
                //System.out.println(Quad);
                sum = sum.add(Quad.pow(2));
            }
            if(sum.toString().equals(bigNumber.getText())) N.isComplete = true;
            bigNumber.setText(sum.toString());
        } else {
            System.out.println("fault");
        }
    }//GEN-LAST:event_FactorActionPerformed

    private void Checks(AprtCleInteger N, int i){
        PowerCheck power = new PowerCheck(N);
        if (power.Check(i) > 1){
            N.SortFactorsPD();
        }
        AprtCle aprt = new AprtCle();
        AprtCleInteger x = new AprtCleInteger(N.getPD(i).toString());
        x.isPrime = aprt.isProbablePrime(x);

        if(x.bitLength() <= 33) x.isPrime = true;
        if (x.isPrime){
              if (N.getType(i) < -TYP_EC)
                  N.setType(i, -N.getType(i));          // Prime
              else if (N.getType(i) < -TYP_LEHMAN)
                  N.setType(i, TYP_LEHMAN);             // Prime 
              else if (N.getType(i) < -TYP_SIQS)
                  N.setType(i, TYP_SIQS);               // Prime 
              else if (N.getType(i) < -TYP_AURIF)
                  N.setType(i, TYP_AURIF);              // Prime 
              else
                  N.setType(i, 0);                      // Prime
        } else {
              if (N.getType(i) < -TYP_EC)
                  N.setType(i, -TYP_EC - N.getType(i));     // Composite 
              else
                  N.setType(i, -N.getType(i));              // Composite 
        }
    }
    
    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        theStack = new Deque();
        bigNumber.setText("");
        op = null;
    }//GEN-LAST:event_ClearActionPerformed

    private void UpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpActionPerformed
        try {
            theStack.addToFront(theStack.removeFromBack());
            bigNumber.setText(((LargeInteger)theStack.getFront()).toString());
        } catch (EmptyDequeException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_UpActionPerformed

    private void DownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownActionPerformed
        try {
            theStack.addToBack(theStack.removeFromFront());
            bigNumber.setText(((LargeInteger)theStack.getFront()).toString());
        } catch (EmptyDequeException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DownActionPerformed

    private void RemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemActionPerformed
        op = new Remainder();
        theStack.addToFront(new LargeInteger(bigNumber.getText()));
    }//GEN-LAST:event_RemActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        LargeInteger x = new LargeInteger(bigNumber.getText());
        LargeInteger y = LargeInteger.pow(2, x);
        bigNumber.setText(y.toString());
        theStack.addToFront(y);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        LargeInteger x = new LargeInteger(bigNumber.getText());
        LargeInteger y = LargeInteger.pow(10, x);
        bigNumber.setText(y.toString());
        theStack.addToFront(y);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void DivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivideActionPerformed
        op = new Divide();
        theStack.addToFront(new LargeInteger(bigNumber.getText()));
    }//GEN-LAST:event_DivideActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        bigNumber.replaceSelection("4");
        bigNumber.requestFocus();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        bigNumber.replaceSelection("8");
        bigNumber.requestFocus();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        bigNumber.replaceSelection("9");
        bigNumber.requestFocus();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        bigNumber.replaceSelection("6");
        bigNumber.requestFocus();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        bigNumber.replaceSelection("3");
        bigNumber.requestFocus();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void MultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplyActionPerformed
        op = new Multiply();
        theStack.addToFront(new LargeInteger(bigNumber.getText()));
    }//GEN-LAST:event_MultiplyActionPerformed

    private void SubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubActionPerformed
        op = new Subtract();
        theStack.addToFront(new LargeInteger(bigNumber.getText()));
    }//GEN-LAST:event_SubActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        op = new Add();
        theStack.addToFront(new LargeInteger(bigNumber.getText()));
    }//GEN-LAST:event_AddActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        bigNumber.replaceSelection("0");
        bigNumber.requestFocus();
    }//GEN-LAST:event_jButton0ActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        bigNumber.setText("");
    }//GEN-LAST:event_DeleteActionPerformed

    private void EnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterActionPerformed
        try {
            LargeInteger y = new LargeInteger(bigNumber.getText());
            bigNumber.setText(y.toString());
            LargeInteger[] operands = {(LargeInteger)theStack.getFront(), y};
            y = (LargeInteger)op.doOperation(operands);
            bigNumber.setText(y.toString());
        } catch (EmptyDequeException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassCastException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        theStack.addToFront(new LargeInteger(bigNumber.getText()));
    }//GEN-LAST:event_EnterActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        bigNumber.replaceSelection("7");
        bigNumber.requestFocus();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        bigNumber.replaceSelection("5");
        bigNumber.requestFocus();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        bigNumber.replaceSelection("1");
        bigNumber.requestFocus();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        bigNumber.replaceSelection("2");
        bigNumber.requestFocus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void PowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerActionPerformed
        op = new Power();
        theStack.addToFront(new LargeInteger(bigNumber.getText()));
    }//GEN-LAST:event_PowerActionPerformed

    private void SignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignActionPerformed
        LargeInteger x = new LargeInteger(bigNumber.getText()).negate();
        bigNumber.setText(x.toString());
        theStack.addToFront(x);
    }//GEN-LAST:event_SignActionPerformed

    private void TotientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotientActionPerformed
        if(N == null || !N.isComplete)
            FactorActionPerformed(null);
        bigNumber.setText(N.Totient().toString());
    }//GEN-LAST:event_TotientActionPerformed

    private void MobiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MobiusActionPerformed
        if(N == null || !N.isComplete)
            FactorActionPerformed(null);
        bigNumber.setText(String.valueOf(N.Moebius()));
    }//GEN-LAST:event_MobiusActionPerformed

    private void SumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumActionPerformed
        if(N == null || !N.isComplete)
            FactorActionPerformed(null);
        bigNumber.setText(N.Sum().toString());
    }//GEN-LAST:event_SumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Clear;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Divide;
    private javax.swing.JButton Down;
    private javax.swing.JButton Enter;
    private javax.swing.JButton Factor;
    private javax.swing.JButton Mobius;
    private javax.swing.JButton Multiply;
    private javax.swing.JButton Power;
    private javax.swing.JButton Rem;
    private javax.swing.JButton Sign;
    private javax.swing.JButton Sub;
    private javax.swing.JButton Sum;
    private javax.swing.JButton Totient;
    private javax.swing.JButton Up;
    private javax.swing.JTextField bigNumber;
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables
}
