PACKAGE = j51.images

SOURCE  = Cpu.gif laf.gif stop.gif load.gif exit.gif tools.gif step.gif \
	stepinto.gif play.gif reset.gif erase.gif file.gif debug.gif load.gif

MAIN = 

include $(JAVA_DEV_ROOT)/Makefile
